### ISSUE TITLE
求新功能

### ISSUE THREAD

**Issue by keywet06** [luosiwei-cmd/CarYon#4]
求生成图、树、字符串的函数

**Comment by luosiwei-cmd** [comment]
您好，有关于生成字符串的函数，详情见这个 [Wiki](https://github.com/luosiwei-cmd/CarYon/wiki/%E5%85%B6%E4%BB%96%E9%9A%8F%E6%9C%BA%E5%87%BD%E6%95%B0)

**Comment by luosiwei-cmd** [comment]
关于图您想要的是随机图，可以指定连不连通的是吗？

**Comment by luosiwei-cmd** [comment]
树的话在安排了

**Comment by luosiwei-cmd** [comment]
感谢您对鄙人小项目的支持！

**Comment by keywet06** [comment]
感谢您对出题者的支持 awa

**Comment by luosiwei-cmd** [comment]
您可以先选择 follow 本项目，到时候有变动您会收到通知的！

**Comment by luosiwei-cmd** [comment]
您好，新功能开发完毕，[wiki](https://github.com/luosiwei-cmd/CarYon/wiki/%E5%9B%BE%E5%92%8C%E6%A0%91-Graph-and-tree)

**Comment by luosiwei-cmd** [comment]
您先试试，现在还是pre-release版本，如果有问题再反馈哈

**Comment by luosiwei-cmd** [comment]
这个 issue 您看到之后就可以close了~有问题再开

感谢您的支持！

**Comment by luosiwei-cmd** [comment]
如果可以的话，请点一颗小star~

**Comment by luosiwei-cmd** [comment]
您好，由于您超过48小时没有回复，该 issue 将被关闭，如果有需要，请reopen，谢谢！
